### ISSUE TITLE
Left margin on iOS a bit too wide

### ISSUE THREAD

**Issue by sts10** [scidsg/hushline-docs#11]
![ios-margins](https://github.com/scidsg/hushline-docs/assets/4871664/53e9d4b9-175b-4c57-8aa9-d70eb586b349)

When I open the docs live site on my iPhone in Safari, I see a wide blank space on the left side of the screen. I assume this is the result of a margin adjustment?

**Comment by glenn-sorrentino** [comment]
Updated with new breakpoints for smaller screens:
```
@media only screen and (max-width: 768px) {
	.content main {
		margin-left: auto;
		margin-right: auto;
	}
	.searchbar-outer,
	.searchresults-outer {
		margin-left: auto;
	}
	.page {
		padding: 0 2.5rem;
	}
}
```
