### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by sts10** [scidsg/hushline-docs#2]
Seeing as this repo mostly contains documentation and not much code, I don't think the Unlicense, which is intended for use with software, is a great fit. 

Instead, I'd consider a Creative Commons license like [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or, if we want copiers to give us attribution, [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). 

(There's also the [GNU Free Documentation License](https://www.gnu.org/licenses/#FDL), but it's, broadly speaking, a copyleft license and thus fundamentally different from both the Unlicense and CC0, plus I not very familiar with it.)

**Comment by sts10** [comment]
I should note that [SecureDrop's documentation](https://github.com/freedomofpress/securedrop-docs/) is [available under the AGPL v3](https://github.com/freedomofpress/securedrop-docs/blob/main/LICENSE), which I would consider a software license like the Unlicense, but maybe it's a bit more lax on the media it covers...

**Comment by glenn-sorrentino** [comment]
https://github.com/scidsg/hushline-docs/blob/main/LICENSE.md
