### ISSUE TITLE
Improve Text Visibility in Table on Verification Page

### ISSUE THREAD

**Issue by iAnonymous3000** [scidsg/hushline-docs#21]
The text color within the table on the verification page provides insufficient contrast against the dark background, making the content difficult to read for users.

- **Issue**: Low contrast text in the table on the verification page.
- **URL**: https://scidsg.github.io/hushline-docs/book/hosted/verification.html
- **Location**: The issue is present in the table under the section 'Verification Categories'.
- **Screenshot**: Attached (the screenshot you have provided).

**Steps to Reproduce**:
1. Navigate to [Verification Page](https://scidsg.github.io/hushline-docs/book/hosted/verification.html).
2. Scroll down to the 'Verification Categories' section.
3. Observe the text visibility issue within the table.

**Expected Result**: 
Text should be easily readable with high contrast for accessibility purposes.

**Actual Result**: 
Text is difficult to read due to low contrast, specifically dark text on a dark background.

**Suggested Fix**: 
Adjust the text color to #FFFFFF (white) for dark backgrounds or change the background color to a lighter shade to maintain a contrast ratio of at least 4.5:1 as recommended by WCAG guidelines.

**Environment**:
- **OS**: Pop!_OS 22.04 LTS
- **Browser**: Brave Browser v1.63.162

**Reference**:
![Screenshot from 2024-02-27 14-28-34](https://github.com/scidsg/hushline-docs/assets/32236127/4cd1826a-103b-4ebd-923a-e263d9a5d768)

**Comment by glenn-sorrentino** [comment]
Fixed. Added background color to table elements.

**Comment by glenn-sorrentino** [comment]
![Screenshot 2024-02-27 at 11 49 01 AM](https://github.com/scidsg/hushline-docs/assets/28545431/cb6826bd-2cc7-4556-aba1-ce483530d349)
![Screenshot 2024-02-27 at 11 49 06 AM](https://github.com/scidsg/hushline-docs/assets/28545431/00fedaf4-85f5-47b5-ad07-3eafc695187a)
